import argparse
import asyncio
import os
from src.utils import setup_logging, ensure_dir_exists
from src.llm_wrapper import LLMWrapper
from src.voice_engine import VoiceEngine
from src.asset_manager import AssetManager
from src.video_editor import VideoEditor
from src.youtube_uploader import YouTubeUploader

logger = setup_logging()

async def main():
    parser = argparse.ArgumentParser(description="Future Forge Automation Engine")
    parser.add_argument("--dry-run", action="store_true", help="Generate video but do not upload")
    parser.add_argument("--topic", type=str, help="Specific topic to generate")
    parser.add_argument("--type", type=str, choices=["long", "short"], default="long", help="Type of video to generate")
    args = parser.parse_args()

    logger.info("Starting Daily Automation...")
    ensure_dir_exists("temp")
    ensure_dir_exists("output")

    # 1. Generate Content (Psychology Niche)
    llm = LLMWrapper()
    
    title = args.topic
    if not title:
        cache_file = "output/psychology_titles.json"
        titles = []
        
        # Try to load from cache first
        if os.path.exists(cache_file):
            logger.info(f"Loading titles from cache: {cache_file}")
            try:
                import json
                with open(cache_file, 'r') as f:
                    titles = json.load(f)
            except Exception as e:
                logger.warning(f"Failed to load cache: {e}")
        
        # If no cache or empty, generate new
        if not titles:
            logger.info("Generating Psychology Titles...")
            titles = llm.generate_psychology_titles()
            if not titles:
                logger.error("Failed to generate titles")
                return
            
            # Save to cache
            ensure_dir_exists("output")
            import json
            with open(cache_file, 'w') as f:
                json.dump(titles, f, indent=2)
            logger.info(f"Titles saved to cache: {cache_file}")
        
        # Select a random title to ensure variety every day
        import random
        title = random.choice(titles)
        
        # Log selected title
        logger.info(f"Selected Title: {title}")
    
    logger.info(f"Generating {args.type} script for Title: {title}")
    
    if args.type == "long":
        script_data = llm.generate_psychology_script(title)
    else:
        script_data = llm.generate_psychology_short_script(title)

    if not script_data:
        logger.error(f"Failed to generate {args.type} script")
        return

    logger.info(f"Title: {script_data.get('title')}")
    if script_data.get('deduced_angle'):
        logger.info(f"Deduced Angle: {script_data.get('deduced_angle')}")
    
    # 2. Process Scenes
    voice = VoiceEngine()
    asset_mgr = AssetManager()
    processed_scenes = []

    for i, scene in enumerate(script_data['scenes']):
        logger.info(f"Processing Scene {i+1}...")
        
        # Audio
        audio_path = f"temp/audio_{i}.mp3"
        await voice.generate_audio(scene['text'], audio_path)
        
        # Visuals
        # Use landscape for long-form, portrait for shorts
        orientation = "landscape" if args.type == "long" else "portrait"
        video_url = asset_mgr.search_video(scene['visual_keyword'], orientation=orientation)
        video_path = f"temp/video_{i}.mp4"
        if video_url:
            asset_mgr.download_file(video_url, video_path)
        else:
            logger.warning(f"No video found for {scene['visual_keyword']}")
        
        processed_scenes.append({
            'audio_path': audio_path,
            'video_path': video_path,
            'text': scene['text']
        })

    # 3. Create Video
    editor = VideoEditor()
    output_file = f"output/final_{args.type}.mp4"
    logger.info("Rendering video...")
    is_short = (args.type == "short")
    success = editor.create_video(processed_scenes, output_file, is_short=is_short)
    
    if success:
        logger.info(f"Video generated successfully: {output_file}")
    else:
        logger.error("Video generation failed")

    if not args.dry_run and success:
        logger.info("Starting Upload Process...")
        try:
            uploader = YouTubeUploader()
            description = f"{script_data.get('title')}\n\nGenerated by Future Forge AI.\n\n#AI #FutureTech #Technology"
            
            video_id = uploader.upload_video(
                output_file, 
                script_data.get('title'), 
                description, 
                privacy_status="public" # Upload as public by default
            )
            if video_id:
                logger.info(f"Successfully uploaded video: https://youtu.be/{video_id}")
        except Exception as e:
            logger.error(f"Upload process failed: {e}")

if __name__ == "__main__":
    asyncio.run(main())

